# train and val data as 1) directory: path/images/, 2) file: path/images.txt, or 3) list: [path1/images/, path2/images/]
# path: ../
train: ../images/Train  # 118287 images
val: ../images/Validation  # 5000 images
test: ../images/Test  # 20288 of 40670 images, submit to https://competitions.codalab.org/competitions/20794

# number of classes
nc: 1

# class names
names: ['lesion']